name: homeconnect
description: HomeConnectApi is a Dart package that provides a client for the Home Connect API, allowing users to interact with their home appliances. It supports authentication, CRUD operations, event subscriptions, and more. 
version: 0.0.2
homepage: https://github.com/KitchenStories/flutter_home_connect_sdk/tree/main/homeconnect

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  json_annotation: ^4.8.0
  eventsource: ^0.4.0
  mockito: ^5.3.2
  oauth2: ^2.0.1
  test: ^1.16.0
  eventify: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

