name: homeconnect_flutter
description: Flutter utility classes, meant to be used with the home connect SDK
version: 0.1.0
homepage: https://github.com/KitchenStories/flutter_home_connect_sdk/tree/main/homeconnect_flutter
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  json_annotation: ^4.8.0
  eventsource: ^0.4.0
  oauth2: ^2.0.1
  homeconnect: ^0.1.0
  webview_flutter: ^4.0.5
  shared_preferences: ^2.0.18

dev_dependencies:
  mockito: ^5.3.2
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

